# Constants

# Scene keys:
SCENE_SPLASH = 'splash'
SCENE_PLAY = 'play'
SCENE_RESULTS = 'results'

CELLSIZE = 20
N_CELLS_WIDE = 32
N_CELLS_HIGH = 24
GAME_FONT = 'freesansbold.ttf'

WINDOW_WIDTH = N_CELLS_WIDE * CELLSIZE  # 640
WINDOW_HEIGHT = N_CELLS_HIGH * CELLSIZE  # 480

BLACK = (0,   0,   0)
DARKGRAY = (40,  40,  40)
RED = (255,   0,   0)
DARKGREEN = (0, 155,   0)
GREEN = (0, 255,   0)
WHITE = (255, 255, 255)
TEAL = (117, 255, 255)

BACKGROUND = BLACK

FRAMES_PER_SECOND = 12

GAME_OVER = 'game over'
KEEP_GOING = 'keep going'

STATE_START = 'start'
STATE_PLAY = 'play'
STATE_END = 'end'